version: 1.0.{build}
build:
  verbosity: minimal

environment:
  matrix:
  - CMAKE_GENERATOR: Unix Makefiles
    BUILD_TYPE: Release
    APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
  - CMAKE_GENERATOR: Visual Studio 15 2017
    BUILD_TYPE: Release
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
  - CMAKE_GENERATOR: Visual Studio 15 2017 Win64
    BUILD_TYPE: Release
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

before_build:
  - cmd: git submodule update --init --recursive
  - sh: git submodule update --init --recursive

build_script:
  - cmd: mkdir build
  - cmd: cd build
  - cmd: cmake .. -G "%CMAKE_GENERATOR%" -DCMAKE_BUILD_TYPE="%BUILD_TYPE%"
  - cmd: cmake --build . --config "%BUILD_TYPE%"
  - cmd: cd ../bin/%BUILD_TYPE%
  - cmd: pattern-bench.exe --size=800000 --tests=512 --full

  - sh: mkdir build
  - sh: cd build
  - sh: cmake .. -G "$CMAKE_GENERATOR" -DCMAKE_BUILD_TYPE="$BUILD_TYPE"
  - sh: cmake --build . --config "$BUILD_TYPE"
  - sh: ../bin/pattern-bench --size=800000 --tests=512 --full
