version: 1.0.{build}
build:
  verbosity: minimal

environment:
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
    CMAKE_GENERATOR: Unix Makefiles

  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    CMAKE_GENERATOR: Visual Studio 15 2017

  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    CMAKE_GENERATOR: Visual Studio 15 2017 Win64

before_build:
  - cmd: git submodule update --init --recursive
  - sh: git submodule update --init --recursive

build_script:
  - cmd: mkdir build
  - cmd: cd build
  - cmd: cmake .. -G "%CMAKE_GENERATOR%" -DCMAKE_BUILD_TYPE=Release
  - cmd: cmake --build . --config Release
  - cmd: cd ../bin/Release
  - cmd: pattern-bench.exe --size=0x800000 --tests=512 --full

  - sh: mkdir build
  - sh: cd build
  - sh: cmake .. -G "$CMAKE_GENERATOR" -DCMAKE_BUILD_TYPE=Release
  - sh: cmake --build . --config Release
  - sh: ../bin/pattern-bench --size=0x800000 --tests=512 --full
